### ISSUE TITLE
NoMethodError:  method `mountable?'

### ISSUE THREAD

**Issue by campbecf** [seanpdoyle/ember-cli-rails-deploy-redis#7]
ember-cli-rails 7.3 and ember-cli-rails-deploy-redis 0.1.1 I get this when trying to deploy.

``````
rake aborted!
NoMethodError:  method `mountable?' for #<EmberCli::Deploy::Redis:0x007f5021a3d130>
/app/vendor/bundle/ruby/2.3.0/gems/ember-cli-rails-0.7.3/lib/ember_cli/app.rb:83:in `mountable?'
/app/vendor/bundle/ruby/2.3.0/gems/ember-cli-rails-0.7.3/lib/ember_cli/route_helpers.rb:27:in `mount_ember_assets'
/app/vendor/bundle/ruby/2.3.0/gems/ember-cli-rails-0.7.3/lib/ember_cli/route_helpers.rb:21:in `mount_ember_app'
/app/config/routes.rb:139:in `block in <top (required)>'
/app/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.5.2/lib/action_dispatch/routing/route_set.rb:432:in `instance_exec'
/app/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.5.2/lib/action_dispatch/routing/route_set.rb:432:in `eval_block'
/app/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.5.2/lib/action_dispatch/routing/route_set.rb:410:in `draw'
/app/config/routes.rb:4:in `<top (required)>'```
``````

**Comment by campbecf** [comment]
Looks like it was fixed in c3974eff79b1d968655cae0c801ad48366e4cce0 but isn't part of a release yet.

**Comment by mikeys** [comment]
:+1:  would be nice if you add it to `rubygems.org` :)

**Comment by henrymazza** [comment]
Got bitten by that one too. `rubygems.org` version doesn’t let you use redis in development.
